Ported the plugin youtube.py from branch master
AmanoTeam/EduuRobot pull request #136
Opened 2021-02-03 13:52 UTC by HitaloSama

This plugin has not been tested on EduuRobot, I did tests on my bot (PyKorone) only if there is any compatibility error with the base of EduuRobot let me know.

2021-02-04 06:59 UTC, alissonlauffer requested changes
Overall it looks good, but there are some issues I can see for now:
 - youtube-dl is missing in requirements.txt file.
 - You've added ytdl to commands list but forgot to create a description for it.
 - youtube-dl is not running in an executor and will block the pool (see userlixo-rfc ytdl.py).

About the second one:
You must create a new json file in `locales/en-GB/youtube.py` with:

```json
{
    "ytdl_description": "command description here"
}
```

2021-02-04 07:10 UTC, alissonlauffer commented on plugins/youtube.py
> +                duration=yt["duration"],
```suggestion
                duration=int(yt["duration"]),
```

Pyrogram uses ints for duration, whereas youtube-dl uses floats. This resolves the `AttributeError: 'float' object has no attribute 'to_bytes'` Exception

2021-02-08 02:15 UTC, alissonlauffer commented
Any update on this? Thanks.

2021-02-08 11:14 UTC, HitaloSama commented
@alissonlauffer i tested what you told me for youtube-dl to be async but it didn't help, easily someone could kill the bot or slow down.

2021-02-08 11:18 UTC, closed without merging